#!/bin/bash
# Commandes utiles pour travailler avec les tests et KPI

echo "🚀 AZO OCR Prototype - Commandes Utiles"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 TESTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Exécuter tous les tests"
echo "pytest test/ -v"
echo ""
echo "# Exécuter seulement les tests unitaires"
echo "pytest test/ -v -m unit"
echo ""
echo "# Exécuter seulement les tests d'intégration"
echo "pytest test/ -v -m integration"
echo ""
echo "# Exécuter avec couverture de code"
echo "pytest test/ --cov=app --cov-report=term-missing --cov-report=html"
echo ""
echo "# Exécuter un fichier de test spécifique"
echo "pytest test/test_validation.py -v"
echo ""
echo "# Exécuter une classe de test"
echo "pytest test/test_normalization.py::TestCleanAmountString -v"
echo ""
echo "# Exécuter un test spécifique"
echo "pytest test/test_validation.py::TestInvoiceDataValidation::test_valid_invoice_creates_successfully -v"
echo ""
echo "# Via le script fourni"
echo "bash run_tests.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 KPI & MONITORING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Consulter les KPI via l'API"
echo "curl http://127.0.0.1:8000/api/v1/kpi | jq"
echo ""
echo "# Analyser les KPI (génère rapport)"
echo "python analyze_kpi.py"
echo ""
echo "# Afficher les KPI brutes (JSONL)"
echo "cat resultats/kpi.jsonl | jq ."
echo ""
echo "# Compter le nombre d'extractions"
echo "cat resultats/kpi.jsonl | wc -l"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 API & SERVEUR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Lancer le serveur"
echo "uvicorn app.main:app --reload"
echo ""
echo "# Accéder à Swagger UI"
echo "open http://127.0.0.1:8000/docs"
echo ""
echo "# Tester l'endpoint /extract"
echo "curl -X POST -F \"file=@sample.pdf\" http://127.0.0.1:8000/api/v1/extract | jq"
echo ""
echo "# Tester l'endpoint /health"
echo "curl http://127.0.0.1:8000/health"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 GESTION DE PROJET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Lancer le pipeline de test complet"
echo "python test/test_pipeline.py"
echo ""
echo "# Vérifier la qualité du code"
echo "python -m pylint app/ --disable=all --enable=E,F"
echo ""
echo "# Formater le code"
echo "black app/ test/"
echo ""
echo "# Vérifier les imports"
echo "python -m isort --check-only app/ test/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Lire la documentation des tests"
echo "cat test/README.md"
echo ""
echo "# Lire la documentation des KPI"
echo "cat KPI.md"
echo ""
echo "# Lire le résumé d'implémentation"
echo "cat IMPLEMENTATION_SUMMARY.md"
echo ""
echo "# Lire le changelog détaillé"
echo "cat CHANGELOG_TESTS_KPI.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💾 DONNÉES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Afficher les résultats d'extraction (CSV)"
echo "head -20 resultats/extractions.csv"
echo ""
echo "# Afficher les KPI brutes (JSONL)"
echo "head -5 resultats/kpi.jsonl | jq ."
echo ""
echo "# Supprimer les anciens résultats"
echo "rm resultats/*.csv resultats/*.jsonl resultats/*.csv"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ À SAVOIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 39 tests disponibles (unitaires + intégration)"
echo "✅ KPI collectées en temps réel (format JSONL)"
echo "✅ Endpoint KPI exposé : GET /api/v1/kpi"
echo "✅ Script d'analyse : python analyze_kpi.py"
echo "✅ Fixtures réutilisables : fixtures/* dans conftest.py"
echo "✅ Mocking OpenAI : @patch('app.services.llm_client.OpenAI')"
echo "✅ Markers : @pytest.mark.unit / integration / slow"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
